### ISSUE TITLE
Sharing reverse engenering

### ISSUE THREAD

**Issue by jeyremy** [lb544/ha-aircloud#2]
Hey @lb544, 

i was wondering, do you have any working postman collection, or endpoint list of your reverse engenering ? 
i'm more a nodeJS guy, so i'm using homebridge. 
If i have time i could use some of your knowledge to make my own plugin in homebridge side

Thanks in advance for your time.

**Comment by lb544** [comment]
Hi,
Sorry for the delay
I use Fiddler and a patched airCloud apk to analyze websocket requests and answers

I only use this in postman to debug : 

![image](https://user-images.githubusercontent.com/56821713/220871387-1f71ea8c-12c0-4a62-be58-b5222901aa2d.png)

;)

**Comment by jeyremy** [comment]
thanks
