### ISSUE TITLE
probleme identification

### ISSUE THREAD

**Issue by 889laurent** [lb544/ha-aircloud#3]
j'ai testé avec mon mail +mdb en clair et en base 64 et erreur ? est ce que l'api fonctionne encore ?

**Comment by lb544** [comment]
Bonsoir
L'api fonctionne mais il faut parfois plusieurs essais
Une nouvelle version arrive bientôt avec des retry pour les actions car je dois envoyer jusqu'à 5x la commande ON pour que ça fonctionne en ce moment

**Comment by 889laurent** [comment]
a priori en claire le token remonte mais ensuite erreur

**Comment by 889laurent** [comment]
Merci pour votre aide Voila la commande et le résultat

le mdp et login en clair dans le script

pas de retour avec websocatdebug
root@JeedomAtlas:/# sh aircloud.sh on Sejour Heating 22
aircloud.sh: 12: [: Sejour: unexpected operator
aircloud.sh: 17: aircloud.sh: -b: not found
aircloud.sh: 27: aircloud.sh: -b: not found
jq: error: syntax error, unexpected ')' (Unix shell quoting issues?) at <top-level>, line 1:
.data[] | select(.id==) | .power
jq: 1 compile error
aircloud.sh: 27: [: =: unexpected operator
{"timestamp":"2023-02-06T18:35:38.374+0000","status":404,"error":"Not Found","message":"No message available","path":"/basic-idu-control/general-control-command/"}

**Comment by 889laurent** [comment]
pour info j'essaye dans un environnement linux Debian

**Comment by 889laurent** [comment]
websocat --version donne websocat 1.11.0

**Comment by lb544** [comment]
Est-ce que la variable vers le binaire websocat est bien définie ?
Exemple : 
websocatbinary="/opt/scripts/websocat.x86_64-unknown-linux-musl" 

Le nom de la pièce est bien celle définie dans l'appli airCloud ? (Case sensitive et accents à prendre en compte)

**Comment by 889laurent** [comment]
Non j'ai pas créer la variable. C'est à mettre dans le script?

**Comment by lb544** [comment]
Oui tout à fait le readme le précise 😉

**Comment by 889laurent** [comment]
Je pensais que c'était pour l'install de websocat . Je vais tester demain . Encore merci pour votre aide

**Comment by 889laurent** [comment]
j'ai simplement rajouter websocatbinary="websocat". J'ai aussi modifier le UUID avec 
uuid=$(uuidgen).
la commande sh aircloud.sh on laurent HEATING 22 fonctionne correctement maintenant, par contre j'ai une erreur 
aircloud.sh: 14: [: laurent: unexpected operator

Pour info, j'ai été obligé de modifier le login avec le mail et pas le numéro de tel. L'appli aircloud propose les 2.
Encore merci pour ce script et pour les futures évolutions.

**Comment by 889laurent** [comment]
après quelques test, quelques petit bug (mais surement du a l'api)
- il faut souvent envoyer la commande plusieurs fois pour quelle passe (mais a priori déja identifié et en cours de correction)
- si on veut seulement modifier la température, il faut passer d'abord par un changement d'état on/off pour prise en compte
- si l'appareil est hors ligne, il retourne encore les anciennes valeurs. Il faudrait peut être prévoir de récupérer l'état ?

**Comment by lb544** [comment]
@889laurent 
J'ai poussé sur une nouvelle branche develop le script avec quelques corrections qui tourne sur mon HA
https://github.com/lb544/ha-aircloud/blob/develop/scripts/aircloud.sh
Les erreurs d'interpretation notamment pour le = et [[ ]] ont été corrigés, je n'avais pas ce bug sur une RedHat like, par contre c'est bien présent sur du Debian Like, c'est corrigé et il n'y a pas l'air d'avoir de régression
J'ai "corrigé" les problèmes d'API en rajoutant une  boucle qui vérifie que le climatiseur est dans l'état  et température attendus
 
J'ai pas encore mis à jour toute la doc mais dans les paramètres du script il faut désormais préciser la vitesse du ventilateur : 

Exemple : 
sh aircloud.sh on Chambre HEATING 19 AUTO
ou
sh aircloud.sh off Chambre HEATING 19 LV1

(LV1 à LV4 + AUTO)

J'ai un peu mis de côté les thermostats internes à HA pour laisser gérer la température par les climatiseurs, on évite ainsi un redémarrage complets des climatiseurs / PAC et donc éviter une usure prématurée du compresseur extérieur (je découvre le monde des clims / PAC, sorry) 

Je passe maintenant par des interrupteurs et sliders + automatismes pour la programmation quotidienne appellant une shell_command générique

shell_command:
  ac_on: sh /opt/scripts/aircloud.sh on {{room}} {{mode}} {{temp}} {{fanspeed}}
  ac_off: sh /opt/scripts/aircloud.sh off {{room}} {{mode}} {{temp}} {{fanspeed}}
  ac_status: sh /opt/scripts/aircloud.sh powerstatus {{room}}

![HA-Panel](https://user-images.githubusercontent.com/56821713/220596805-7e64b202-256b-46aa-bbdf-e7e69ef05f95.JPG)

J'essai de reproduire l'interface de l'appli airCloud pour ne plus l'utiliser et ne passer que par HA qui sera 1000x plus réactif même si le script galère derrière, au moins sur smartphone je ne suis plus bloqué sur du "chargement en cours"

Il faudra en revanche quoi qu'il arrive toujours envoyer une commande "on" pour changer la température, et un "off" avec tous les autres paramètres, l'application airCloud fonctionne ainsi en réalité lors des appels au websocket Hitachi

Dans les bugs connus : 
-  "parse error: Invalid numeric literal at line 1, column 2601" 
   -> jq qui ne parvient pas à parser correctement le json mais la commande passe
- Les climatiseurs / PAC peuvent recevoir plusieurs fois la commande "on" ou "off" occasionnant un bip supplémentaire, lié à la boucle "until" qui ne reçoit pas le statut de la clim via l'API 
- L'API est devenue très lente, je ne sais pas si justement la mise à dispo de mon script a ralenti les serveurs Hitachi ou s'ils ont des protections de leurs côtés également (Les UUID de uuidgenerator.net par exemple étaient bannis, un motif commun à chaque UUID a permis à Hitachi de les bannir)


Je mettrais à jour la doc dès que j'ai le temps

**Comment by 889laurent** [comment]
Merci pour ton job. Je viens de tester, j'ai plus de message d'erreur, mais la commande ne passe pas et le script reste en cours. J'ai tester avec uudid (uuidgen) et j'ai eu un retour avec message d'erreur et la commande passe, mais est renouvellée en continu sans arret du script. J'ai refait un autre essais et plus rien? je pense effectivement que les uuid sont aléatoirement bloqué

**Comment by 889laurent** [comment]
l'erreur lorsque la commande passe en boucle
jeedom@JeedomAtlas:/$ sh aircloud.sh off marc HEATING 22 AUTO
parse error: Invalid numeric literal at line 1, column 7853
{"commandId":"f279ec5c-b2b3-11ed-af4a-0665e10687d3","thingId":"th.1fb2e09464e0-8039-de11-dd2a-37c8434f"}aircloud.sh: 60: [: =: unexpected operator


une autre 
jeedom@JeedomAtlas:/$ sh aircloud.sh on marc HEATING 22 AUTO
aircloud.sh: 44: [: =: unexpected operator
{"commandId":"0dde194b-b2b4-11ed-9fa4-06b80bbb68c3","thingId":"th.1fb2e09464e0-8039-de11-dd2a-37c8434f"}aircloud.sh: 44: [: =: unexpected operator
{"commandId":"1d24029d-b2b4-11ed-9d73-0a9d6d3c9be1","thingId":"th.1fb2e09464e0-8039-de11-dd2a-37c8434f"}^C

{"commandId":"01541b76-b2b4-11ed-9fa4-06b80bbb68c3","thingId":"th.1fb2e09464e0-8039-de11-dd2a-37c8434f"}^C

**Comment by lb544** [comment]
Merci pour ton retour, le script ne doit pas réussir à récupérer l'état des climatiseurs
Peux-tu me faire un retour en executant le paramètre websocatdebug et websocatdebug2 (en cachant les infos sensibles) ? 
sh aircloud.sh websocatdebug
sh aircloud.sh websocatdebug2

Merci

Ce qui m'étonne c'est l'erreur d'opérateur, je ne l'ai pas sur mon raspberry sous Debian Bullseyes ni sur mon serveur dédié sous CentOS 9

**Comment by 889laurent** [comment]
websocatdebug ne retourne rien
websocatdebug2
jeedom@JeedomAtlas:/$ sh aircloud.sh websocatdebug2
CONNECTED
version:1.2
heart-beat:10000,10000
user-name:User(id=26298, email=***@***, phoneNumber=null, password=null, softLockCount=0, lockUntil=null, detailsUserInfo=null, status=null, socialAccounts=[])

**Comment by 889laurent** [comment]
precision si utile, mon login et mdp son en clair dans le script

**Comment by lb544** [comment]
Effectivement il y a l'air d'avoir un blocage après l'authentification sur le websocket
On doit obtenir un résultat de ce type normalement : 

root@raspberrypi:~# sh /opt/aircloud.sh websocatdebug2
CONNECTED
version:1.2
heart-beat:10000,10000
user-name:User(id=*****, email=\*\*\*\**\@gmail.com, phoneNumber=null, password=null, softLockCount=0, lockUntil=null, detailsUserInfo=null, status=null, socialAccounts=[])

MESSAGE
destination:/notification/\*\***/****
content-type:application/json;charset=UTF-8
subscription:<contenu de l'uuid généré>
message-id:****
content-length:2593

{"notificationType":"ON_CONNECT" [...]


Je viens de tester avec le login/mdp en clair ça passe bien chez moi, étonnant

Tu as bien en paramètres : 

hitachiuser="login@mail.com"
hitachipassword="*****"
(avec les doubles quotes entourant les valeurs) 

? 

l'utilitaire jq est bien installé aussi sur la machine ?

**Comment by 889laurent** [comment]
oui jq-1.5-1-a5b5cbe

oui pour 
hitachiuser="[login@mail.com](mailto:login@mail.com)"
hitachipassword="*****"

après bizarre ca marche de manière aléatoire, mais quand ca marche ca boucle

pour websocat j'ai mis websocatbinary="websocat" car j'ai pas de chemin a mettre chez moi

**Comment by lb544** [comment]
Pour la variable websocatbinary c'est OK parce que tu as bien une réponse du websocket 
"jeedom@JeedomAtlas:/$ sh aircloud.sh websocatdebug2
CONNECTED"

Tu aurais une erreur sinon

En revanche, je ne parviens pas à expliquer ton problème, mais le fait que ça boucle ne me choque pas vraiment étant donné que de base tu as déjà des problèmes aléatoires de login, la boucle étant construite sur un résultat du websocket, celui-ci n'étant pas stable chez toi, le script ne le sera pas


Pour avancer, peux-tu décommenter les différents echo dans le script au début : 

echo $uuid
echo $token
echo $familyId
echo $cloudlds

Et voir où ça peut bloquer ? 

A noter que le token doit ressembler à quelque chose de ce type : 

eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIzODcxIiwic2NvcGVzIjpbImFjY2Vzc190b2tlbiJdLCJpYXQiOjE2NzcwNzcyMzAsImlzcyI6Imh0dHBzOi8vYXBpLWdsb2JhbC1wcm9kLmFpcmNsb3V(blabla)TAzMH0.Uj-(blabla)k1XbJ8l6dL8G9sR7AMhdDMg

Il y a 3 éléments séparés par des points dans ce token : 

eyJhbGciOiJIUzUxMiJ9
eyJzdWIiOiIzODcxIiwic2NvcGVzIjpbImFjY2Vzc190b2tlbiJdLCJpYXQiOjE2NzcwNzcyMzAsImlzcyI6Imh0dHBzOi8vYXBpLWdsb2JhbC1wcm9kLmFpcmNsb3V(blabla)TAzMH0
Uj-(blabla)k1XbJ8l6dL8G9sR7AMhdDMg

Avec un base64 decode on devrait obtenir au moins ça : 

root@raspberrypi:~# echo "eyJhbGciOiJIUzUxMiJ9" | base64 -d
{"alg":"HS512"}

root@raspberrypi:~# echo "eyJzdWIiOiIzODcxIiwic2NvcGVzIjpbImFjY2Vzc190b2tlbiJdLCJpYXQiOjE2NzcwNzcyMzAsImlzcyI6Imh0dHBzOi8vYXBpLWdsb2JhbC1wcm9kLmFpcmNsb3V(blabla)TAzMH0" | base64 -d
{"sub":"\<id de ton compte\>","scopes":["access_token"],"iat":1677077550,"iss":"https://api-global-prod.aircloudhome.com/iam","aud":"aircloudglobal-prod","exp":1677079350}

Le dernier élément lui n'est pas lisible humainement

**Comment by 889laurent** [comment]
le retour avec token
 echo "eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIyNjI5OCIsInNjb3BlcyI6WyJhY2Nlc3NfdG9rZW4iXSwiaWF0IjoxNjc3MDgwNTgxLCJpc3MiOiJodHRwczovL2FwaS1nbG9iYWwtcHJvZC5haXJjbG91ZGhvbWUuY29tL2lhbSIsImF1ZCI6ImFpcmNsb3VkZ2xvYmFsLXByb2QiLCJleHAiOjE2NzcwODIzODF9.0Ujxc0"  | base64 -d
{"alg":"HS512"}base64: entrée incorrecte

**Comment by lb544** [comment]
Il récupère bien ton ID de ton compte dans le token, donc le problème n'est pas là non plus
Cet ID doit apparaitre sur la ligne juste en dessous du token lors du websocatdebug2 : 

root@raspberrypi:~# sh /opt/aircloud.sh websocatdebug2
(uuid)
(token)
(id du compte)
(cloud ID's)

**Comment by 889laurent** [comment]
j'avais juste mis le retour du token mais il y a bien toutes les infos et en plus ca marche aléatoirement quand je lance une commande,
le retour websocatdebug2
sh aircloud2.sh websocatdebug2
a31a566f-a151-4c0d-88cb-50e706470671
eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIyNjI5OCIsInNjb3BlcyI6WyJhY2Nlc3NfdG9rZW4iXSwiaWF0IjoxNjc3MDgxNTk4LCJpc3MiOiJodHRwczovL2FwaS1nbG9iYWwtcHJvZC5haXJjbG91ZGhvbWUuY29tL2lhbSIsImF1ZCI6ImFpcmNsb3VkZ2xvYmFsLXByb2QiLCJleHAiOjE2NzcwODMzOTh9.e-E0Mnscn3EWHxlfWp0nEhQ68CxJ-uwUmJ_RC3ALHXqfM29rePyhEnpBuC9OaOg-dUs_4Wt00RN4lqHXmb5kxw
26298
["155_RAK-25RPE","155_","155_RAK-18RPE"]
CONNECTED
version:1.2
heart-beat:10000,10000
user-name:User(id=26298, email=****, phoneNumber=null, password=null, softLockCount=0, lockUntil=null, detailsUserInfo=null, status=null, socialAccounts=[])

**Comment by lb544** [comment]
Une chose que j'ai pas précisé, si le script est utilisé dans HA actuellement, pense à l'enlever pour les tests
Il se peut que HA lance plusieurs fois le script et peut donc spammer l'api et websocket qui te "ban" temporairement

**Comment by 889laurent** [comment]
non il est juste en local sur un linux debian

**Comment by lb544** [comment]
S'il n'est pas encore utilisé par Home Assistant là je sèche un peu 😅
En mode debug il passe quasiment tout le temps de mon côté
Je réfléchis à ce qui pourrait poser problème mais là je ne vois pas trop hormis l'api et websocket qui filtre un peu trop
Je ne transmets pas d'infos qui seraient spécifiques à mon compte dans le script 
Mystère ...
A la rigueur si tu le souhaites je peux te proposer en privé de tester avec ton compte (avec un mot de passe temporaire bien sûr) sur mon installation au moins un websocatdebug pour voir le comportement

**Comment by 889laurent** [comment]
merci volontiers. je te les donnes en ,MP

**Comment by 889laurent** [comment]
je peux avoir ton mail (le mien laurent.mario@valtinee.fr)

**Comment by lb544** [comment]
Je viens de t'envoyer un mail 😉

**Comment by lb544** [comment]
Problème identifié : Timeout de websocat trop court, passage de 2 à 5s
Script à jour (en cours de développement et tests encore) : 
https://github.com/lb544/ha-aircloud/blob/develop/scripts/aircloud.sh
